[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
skip = [".gitignore", ".dockerignore"]
extend_skip = [".md", ".json"]
skip_glob = ["docs/*", "tests/*"]
extend_skip_glob = ["my_*_module.py", "test/*", "test_*.py", "*_test.py"]
line_length = 88
include_trailing_comma = true
use_parentheses = true
